# Generated by Django 4.1.5 on 2023-02-06 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='concertModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('SingerName', models.CharField(max_length=100)),
                ('length', models.IntegerField()),
                ('Poster', models.ImageField(null=True, upload_to='ConcertImages/')),
            ],
            options={
                'verbose_name': 'کنسرت',
                'verbose_name_plural': 'کنسرتها',
            },
        ),
        migrations.CreateModel(
            name='locationModel',
            fields=[
                ('IdNumber', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Adress', models.CharField(default='تهران - برج میلاد', max_length=500)),
                ('Phone', models.CharField(max_length=11, null=True)),
                ('capacity', models.IntegerField()),
                ('test', models.CharField(max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'محل برگزاری',
                'verbose_name_plural': 'محل برگزاری',
            },
        ),
        migrations.CreateModel(
            name='ProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Family', models.CharField(max_length=100)),
                ('ProfileImage', models.ImageField(upload_to='ProfileImage/')),
                ('Gender', models.IntegerField(choices=[('Man', 'مرد'), ('Women', 'زن')])),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربر',
            },
        ),
        migrations.CreateModel(
            name='timeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StartDateTime', models.DateTimeField()),
                ('Seats', models.IntegerField()),
                ('Status', models.IntegerField(choices=[(1, 'فروش بلیط شروع شده '), (2, 'فروش بلیط تمام شده'), (3, 'این سانس کنسل شده'), (4, 'درحال فروش بلیط')], verbose_name=',عیت')),
                ('concertModel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ticketSales.concertmodel')),
                ('locationModel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ticketSales.locationmodel')),
            ],
            options={
                'verbose_name': 'سانس',
                'verbose_name_plural': 'سانس',
            },
        ),
        migrations.CreateModel(
            name='ticketModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticketImage', models.ImageField(upload_to='TicketImage/', verbose_name='عکس')),
                ('Name', models.CharField(max_length=100, verbose_name='عنوان')),
                ('Price', models.IntegerField(verbose_name='مبلغ')),
                ('ProfileModel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ticketSales.profilemodel', verbose_name='کاربر')),
                ('timeModel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ticketSales.timemodel', verbose_name='سانس')),
            ],
            options={
                'verbose_name': 'بلیط',
                'verbose_name_plural': 'بلیط',
            },
        ),
    ]
